# UT Bot Monitor Configuration - Multi Exchange Support

# 交易所配置
exchanges:
  okx:
    name: "okx"
    enable_rate_limit: true
    enabled: true
  hyperliquid:
    name: "hyperliquid"
    enable_rate_limit: true
    enabled: true

monitoring:
  trigger_second: 10        # 触发秒数（每个周期的第xx秒启动）
  trigger_minutes: 5        # 触发间隔（分钟）- 绝对时间触发，如每小时的5m10s, 10m10s, 15m10s等
  fetch_limit: 1000         # 抓取数据条数
  tail_calc: 1000          # 计算指标保留最近行数
  max_retries: 5           # API请求最大重试次数
  retry_delay: 5           # 重试延迟时间（秒）
  max_workers: 2          # 新增：最大线程数配置
  use_multi_thread: true   # 使用多线程模式
  
  # 监控目标配置（支持多币种、多时间框架、多交易所）
  targets:
    # OKX 监控目标
    - exchange: "okx"
      symbol: "BTC/USDT:USDT"
      timeframe: "15m"
      enabled: true
      csv_raw: "okx/data_raw/BTC/btc_15m_latest.csv"
      csv_utbot: "okx/data_utbot/BTC/btc_15m_latest_utbotv5.csv"

    - exchange: "okx"
      symbol: "BTC/USDT:USDT"
      timeframe: "5m"
      enabled: true
      csv_raw: "okx/data_raw/BTC/btc_5m_latest.csv"
      csv_utbot: "okx/data_utbot/BTC/btc_5m_latest_utbotv5.csv"

    - exchange: "okx"
      symbol: "ETH/USDT:USDT"
      timeframe: "15m"
      enabled: true
      csv_raw: "okx/data_raw/ETH/eth_15m_latest.csv"
      csv_utbot: "okx/data_utbot/ETH/eth_15m_latest_utbotv5.csv"

    - exchange: "okx"
      symbol: "ETH/USDT:USDT"
      timeframe: "5m"
      enabled: true
      csv_raw: "okx/data_raw/ETH/eth_5m_latest.csv"
      csv_utbot: "okx/data_utbot/ETH/eth_5m_latest_utbotv5.csv"

    - exchange: "okx"
      symbol: "SOL/USDT:USDT"
      timeframe: "15m"
      enabled: true
      csv_raw: "okx/data_raw/SOL/sol_15m_latest.csv"
      csv_utbot: "okx/data_utbot/SOL/sol_15m_latest_utbotv5.csv"

    - exchange: "okx"
      symbol: "SOL/USDT:USDT"
      timeframe: "5m"
      enabled: true
      csv_raw: "okx/data_raw/SOL/sol_5m_latest.csv"
      csv_utbot: "okx/data_utbot/SOL/sol_5m_latest_utbotv5.csv"

    # Hyperliquid 监控目标
    - exchange: "hyperliquid"
      symbol: "BTC/USDC:USDC"
      timeframe: "15m"
      enabled: true
      csv_raw: "hyperliquid/data_raw/BTC/btc_15m_latest.csv"
      csv_utbot: "hyperliquid/data_utbot/BTC/btc_15m_latest_utbotv5.csv"

    - exchange: "hyperliquid"
      symbol: "BTC/USDC:USDC"
      timeframe: "5m"
      enabled: true
      csv_raw: "hyperliquid/data_raw/BTC/btc_5m_latest.csv"
      csv_utbot: "hyperliquid/data_utbot/BTC/btc_5m_latest_utbotv5.csv"

    - exchange: "hyperliquid"
      symbol: "ETH/USDC:USDC"
      timeframe: "15m"
      enabled: true
      csv_raw: "hyperliquid/data_raw/ETH/eth_15m_latest.csv"
      csv_utbot: "hyperliquid/data_utbot/ETH/eth_15m_latest_utbotv5.csv"

    - exchange: "hyperliquid"
      symbol: "ETH/USDC:USDC"
      timeframe: "5m"
      enabled: true
      csv_raw: "hyperliquid/data_raw/ETH/eth_5m_latest.csv"
      csv_utbot: "hyperliquid/data_utbot/ETH/eth_5m_latest_utbotv5.csv"

    - exchange: "hyperliquid"
      symbol: "SOL/USDC:USDC"
      timeframe: "15m"
      enabled: true
      csv_raw: "hyperliquid/data_raw/SOL/sol_15m_latest.csv"
      csv_utbot: "hyperliquid/data_utbot/SOL/sol_15m_latest_utbotv5.csv"

    - exchange: "hyperliquid"
      symbol: "SOL/USDC:USDC"
      timeframe: "5m"
      enabled: true
      csv_raw: "hyperliquid/data_raw/SOL/sol_5m_latest.csv"
      csv_utbot: "hyperliquid/data_utbot/SOL/sol_5m_latest_utbotv5.csv"

# 通知配置
notification:
  enabled: true
  websocket:
    enabled: true
    host: "0.0.0.0"      # 监听所有接口
    port: 10000          # WebSocket 端口
    ipv6_enabled: true  # 新增：启用 IPv6 支持
    bind_both: true     # 新增：同时绑定 IPv4 和 IPv6

# Telegram 配置 (可选：也可通过环境变量设置)
telegram:
  enabled: true           # 启用Telegram通知
  bot_token: ""          # 留空则从环境变量获取 TELEGRAM_BOT_TOKEN
  chat_ids: []           # 留空则从环境变量获取 TELEGRAM_CHAT_ID (逗号分隔)

# 策略配置
strategies:
  enabled: ["utbot"]     # 启用的策略列表
  utbot:                 # UT Bot 策略配置
    # 这里可以添加UT Bot特定的配置参数
    enable_sr_analysis: true  # 启用智能S/R分析
    smart_sr_config:          # 智能S/R分析配置
      timeframes: ["15", "60", "240"]  # 分析的时间框架（15分钟、1小时、4小时）
      show_swings: true              # 显示摆动高低点
      show_pivots: false             # 显示枢轴点
      show_fibonacci: false          # 显示斐波那契水平
      show_order_blocks: false       # 显示订单块
      show_volume_profile: false     # 显示成交量分析
      show_psychological_levels: true # 显示心理价位水平
      show_within_percent: 2.5       # 显示价格附近百分比内的水平
      lookback_swings: 3             # 摆动点回看数量
      cluster_percent: 0.25          # 聚类百分比
      top_n: 8                       # 显示前N个区域
      reaction_lookback: 100         # 反应计算回看期
      sort_by: "Confluence"          # 排序方式 ("Confluence", "Reactions", "Distance")
      alert_confluence: 4            # 警报汇聚度阈值
      min_confluence: 2        

# 日志配置
logging:
  enabled: true
  log_file: "logs/signals.log"
  level: "INFO"
  max_file_size_mb: 10
  backup_count: 5
  level: "INFO"