# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import trading_service_pb2 as trading__service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in trading_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TradingServiceStub(object):
    """交易查询服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetChart = channel.unary_unary(
                '/trading.TradingService/GetChart',
                request_serializer=trading__service__pb2.ChartRequest.SerializeToString,
                response_deserializer=trading__service__pb2.ChartResponse.FromString,
                _registered_method=True)
        self.GetExchangeStatus = channel.unary_unary(
                '/trading.TradingService/GetExchangeStatus',
                request_serializer=trading__service__pb2.ExchangeStatusRequest.SerializeToString,
                response_deserializer=trading__service__pb2.ExchangeStatusResponse.FromString,
                _registered_method=True)
        self.GetSupportResistance = channel.unary_unary(
                '/trading.TradingService/GetSupportResistance',
                request_serializer=trading__service__pb2.SRRequest.SerializeToString,
                response_deserializer=trading__service__pb2.SRResponse.FromString,
                _registered_method=True)


class TradingServiceServicer(object):
    """交易查询服务
    """

    def GetChart(self, request, context):
        """获取图表数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExchangeStatus(self, request, context):
        """获取交易所状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSupportResistance(self, request, context):
        """获取支撑阻力位数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetChart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChart,
                    request_deserializer=trading__service__pb2.ChartRequest.FromString,
                    response_serializer=trading__service__pb2.ChartResponse.SerializeToString,
            ),
            'GetExchangeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExchangeStatus,
                    request_deserializer=trading__service__pb2.ExchangeStatusRequest.FromString,
                    response_serializer=trading__service__pb2.ExchangeStatusResponse.SerializeToString,
            ),
            'GetSupportResistance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSupportResistance,
                    request_deserializer=trading__service__pb2.SRRequest.FromString,
                    response_serializer=trading__service__pb2.SRResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trading.TradingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trading.TradingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradingService(object):
    """交易查询服务
    """

    @staticmethod
    def GetChart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/GetChart',
            trading__service__pb2.ChartRequest.SerializeToString,
            trading__service__pb2.ChartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExchangeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/GetExchangeStatus',
            trading__service__pb2.ExchangeStatusRequest.SerializeToString,
            trading__service__pb2.ExchangeStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSupportResistance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/GetSupportResistance',
            trading__service__pb2.SRRequest.SerializeToString,
            trading__service__pb2.SRResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
