# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trading_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'trading_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15trading_service.proto\x12\x07trading\"f\n\x0c\x43hartRequest\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x11\n\ttimeframe\x18\x03 \x01(\t\x12\r\n\x05\x63ount\x18\x04 \x01(\x05\x12\x12\n\ninclude_sr\x18\x05 \x01(\x08\"g\n\rChartResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nchart_data\x18\x03 \x01(\x0c\x12 \n\x07sr_data\x18\x04 \x01(\x0b\x32\x0f.trading.SRData\")\n\x15\x45xchangeStatusRequest\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\"q\n\x16\x45xchangeStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08\x65xchange\x18\x02 \x01(\t\x12\x0e\n\x06online\x18\x03 \x01(\x08\x12\x13\n\x0blast_update\x18\x04 \x01(\x03\x12\x0f\n\x07symbols\x18\x05 \x03(\t\"@\n\tSRRequest\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x11\n\ttimeframe\x18\x03 \x01(\t\"M\n\nSRResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1d\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x0f.trading.SRData\"T\n\x06SRData\x12\x15\n\rcurrent_price\x18\x01 \x01(\x01\x12\x13\n\x0btotal_zones\x18\x02 \x01(\x05\x12\x1e\n\x05zones\x18\x03 \x03(\x0b\x32\x0f.trading.SRZone\"{\n\x06SRZone\x12\r\n\x05level\x18\x01 \x01(\x01\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x12\n\nconfluence\x18\x03 \x01(\x05\x12\x0b\n\x03top\x18\x04 \x01(\x01\x12\x0e\n\x06\x62ottom\x18\x05 \x01(\x01\x12\x0f\n\x07methods\x18\x06 \x03(\t\x12\x12\n\ntimeframes\x18\x07 \x03(\t2\xe2\x01\n\x0eTradingService\x12\x39\n\x08GetChart\x12\x15.trading.ChartRequest\x1a\x16.trading.ChartResponse\x12T\n\x11GetExchangeStatus\x12\x1e.trading.ExchangeStatusRequest\x1a\x1f.trading.ExchangeStatusResponse\x12?\n\x14GetSupportResistance\x12\x12.trading.SRRequest\x1a\x13.trading.SRResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trading_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHARTREQUEST']._serialized_start=34
  _globals['_CHARTREQUEST']._serialized_end=136
  _globals['_CHARTRESPONSE']._serialized_start=138
  _globals['_CHARTRESPONSE']._serialized_end=241
  _globals['_EXCHANGESTATUSREQUEST']._serialized_start=243
  _globals['_EXCHANGESTATUSREQUEST']._serialized_end=284
  _globals['_EXCHANGESTATUSRESPONSE']._serialized_start=286
  _globals['_EXCHANGESTATUSRESPONSE']._serialized_end=399
  _globals['_SRREQUEST']._serialized_start=401
  _globals['_SRREQUEST']._serialized_end=465
  _globals['_SRRESPONSE']._serialized_start=467
  _globals['_SRRESPONSE']._serialized_end=544
  _globals['_SRDATA']._serialized_start=546
  _globals['_SRDATA']._serialized_end=630
  _globals['_SRZONE']._serialized_start=632
  _globals['_SRZONE']._serialized_end=755
  _globals['_TRADINGSERVICE']._serialized_start=758
  _globals['_TRADINGSERVICE']._serialized_end=984
# @@protoc_insertion_point(module_scope)
